In [95]:
import pandas as pd
import numpy as np

In [96]:
df=pd.read_csv('/content/countries of the world.csv')

In [97]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [98]:
df.tail()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
222,West Bank,NEAR EAST,2460492,5860,"419,9","0,00","2,98","19,62",800.0,NaN,"145,2","16,9","18,97","64,13",3,"31,67","3,92","0,09","0,28","0,63"
223,Western Sahara,NORTHERN AFRICA,273008,266000,"1,0","0,42",NaN,NaN,NaN,NaN,NaN,"0,02",0,"99,98",1,NaN,NaN,NaN,NaN,"0,4"
224,Yemen,NEAR EAST,21456188,527970,"40,6","0,36",0,"61,5",800.0,"50,2","37,2","2,78","0,24","96,98",1,"42,89","8,3","0,135","0,472","0,393"
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,"15,3","0,00",0,"88,29",800.0,"80,6","8,2","7,08","0,03","92,9",2,41,"19,93","0,22","0,29","0,489"
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,"31,3","0,00",0,"67,69",1900.0,"90,7","26,8","8,32","0,34","91,34",2,"28,01","21,84","0,179","0,243","0,579"

In [99]:
df.shape

(227, 20)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             227 non-null    object
 1   Region                              227 non-null    object
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          227 non-null    object
 5   Coastline (coast/area ratio)        227 non-null    object
 6   Net migration                       224 non-null    object
 7   Infant mortality (per 1000 births)  224 non-null    object
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object
 10  Phones (per 1000)                   223 non-null    object
 11  Arable (%)                          225 non-null    object
 12  Crops (%)                           225 non-null    object
 13  Other (%)                           225 non-null    object
 14  Climate                             205 non-null    object
 15  Birthrate                           224 non-null    object
 16  Deathrate                           223 non-null    object
 17  Agriculture                         212 non-null    object
 18  Industry                            211 non-null    object
 19  Service                             212 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 35.6+ KB

In [101]:
df.describe()

         Population  Area (sq. mi.)  GDP ($ per capita)
count  2.270000e+02    2.270000e+02          226.000000
mean   2.874028e+07    5.982270e+05         9689.823009
std    1.178913e+08    1.790282e+06        10049.138513
min    7.026000e+03    2.000000e+00          500.000000
25%    4.376240e+05    4.647500e+03         1900.000000
50%    4.786994e+06    8.660000e+04         5550.000000
75%    1.749777e+07    4.418110e+05        15700.000000
max    1.313974e+09    1.707520e+07        55100.000000

In [102]:
df.isna().sum()   #MISSING VALUES COUNT

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [103]:
#CLEANING MISSING VALUES
df.replace('', np.nan, inplace=True)
df.isna().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [104]:
#CHANGE DATATYPE TO DATAFRAME
#1)TO GET COLMS WITH OBJ DATATYP
# object_col=[]
# for i in df:
#   if (df[i].dtype=='object'):
#     object_col.append(i)

# print(object_col)

In [105]:
object_col=[]
for i in df:
  if df[i].dtype=='object':
    object_col.append(i)
    print(f'{i}|{df[i].nunique()}|{df[i].unique()}')
    print('----------------------------------------------------------')

Country|227|['Afghanistan ' 'Albania ' 'Algeria ' 'American Samoa ' 'Andorra '
 'Angola ' 'Anguilla ' 'Antigua & Barbuda ' 'Argentina ' 'Armenia '
 'Aruba ' 'Australia ' 'Austria ' 'Azerbaijan ' 'Bahamas, The ' 'Bahrain '
 'Bangladesh ' 'Barbados ' 'Belarus ' 'Belgium ' 'Belize ' 'Benin '
 'Bermuda ' 'Bhutan ' 'Bolivia ' 'Bosnia & Herzegovina ' 'Botswana '
 'Brazil ' 'British Virgin Is. ' 'Brunei ' 'Bulgaria ' 'Burkina Faso '
 'Burma ' 'Burundi ' 'Cambodia ' 'Cameroon ' 'Canada ' 'Cape Verde '
 'Cayman Islands ' 'Central African Rep. ' 'Chad ' 'Chile ' 'China '
 'Colombia ' 'Comoros ' 'Congo, Dem. Rep. ' 'Congo, Repub. of the '
 'Cook Islands ' 'Costa Rica ' "Cote d'Ivoire " 'Croatia ' 'Cuba '
 'Cyprus ' 'Czech Republic ' 'Denmark ' 'Djibouti ' 'Dominica '
 'Dominican Republic ' 'East Timor ' 'Ecuador ' 'Egypt ' 'El Salvador '
 'Equatorial Guinea ' 'Eritrea ' 'Estonia ' 'Ethiopia ' 'Faroe Islands '
 'Fiji ' 'Finland ' 'France ' 'French Guiana ' 'French Polynesia '
 'Gabon ' 'Gambia, The ' 'Gaza Strip ' 'Georgia ' 'Germany ' 'Ghana '
 'Gibraltar ' 'Greece ' 'Greenland ' 'Grenada ' 'Guadeloupe ' 'Guam '
 'Guatemala ' 'Guernsey ' 'Guinea ' 'Guinea-Bissau ' 'Guyana ' 'Haiti '
 'Honduras ' 'Hong Kong ' 'Hungary ' 'Iceland ' 'India ' 'Indonesia '
 'Iran ' 'Iraq ' 'Ireland ' 'Isle of Man ' 'Israel ' 'Italy ' 'Jamaica '
 'Japan ' 'Jersey ' 'Jordan ' 'Kazakhstan ' 'Kenya ' 'Kiribati '
 'Korea, North ' 'Korea, South ' 'Kuwait ' 'Kyrgyzstan ' 'Laos ' 'Latvia '
 'Lebanon ' 'Lesotho ' 'Liberia ' 'Libya ' 'Liechtenstein ' 'Lithuania '
 'Luxembourg ' 'Macau ' 'Macedonia ' 'Madagascar ' 'Malawi ' 'Malaysia '
 'Maldives ' 'Mali ' 'Malta ' 'Marshall Islands ' 'Martinique '
 'Mauritania ' 'Mauritius ' 'Mayotte ' 'Mexico ' 'Micronesia, Fed. St. '
 'Moldova ' 'Monaco ' 'Mongolia ' 'Montserrat ' 'Morocco ' 'Mozambique '
 'Namibia ' 'Nauru ' 'Nepal ' 'Netherlands ' 'Netherlands Antilles '
 'New Caledonia ' 'New Zealand ' 'Nicaragua ' 'Niger ' 'Nigeria '
 'N. Mariana Islands ' 'Norway ' 'Oman ' 'Pakistan ' 'Palau ' 'Panama '
 'Papua New Guinea ' 'Paraguay ' 'Peru ' 'Philippines ' 'Poland '
 'Portugal ' 'Puerto Rico ' 'Qatar ' 'Reunion ' 'Romania ' 'Russia '
 'Rwanda ' 'Saint Helena ' 'Saint Kitts & Nevis ' 'Saint Lucia '
 'St Pierre & Miquelon ' 'Saint Vincent and the Grenadines ' 'Samoa '
 'San Marino ' 'Sao Tome & Principe ' 'Saudi Arabia ' 'Senegal ' 'Serbia '
 'Seychelles ' 'Sierra Leone ' 'Singapore ' 'Slovakia ' 'Slovenia '
 'Solomon Islands ' 'Somalia ' 'South Africa ' 'Spain ' 'Sri Lanka '
 'Sudan ' 'Suriname ' 'Swaziland ' 'Sweden ' 'Switzerland ' 'Syria '
 'Taiwan ' 'Tajikistan ' 'Tanzania ' 'Thailand ' 'Togo ' 'Tonga '
 'Trinidad & Tobago ' 'Tunisia ' 'Turkey ' 'Turkmenistan '
 'Turks & Caicos Is ' 'Tuvalu ' 'Uganda ' 'Ukraine '
 'United Arab Emirates ' 'United Kingdom ' 'United States ' 'Uruguay '
 'Uzbekistan ' 'Vanuatu ' 'Venezuela ' 'Vietnam ' 'Virgin Islands '
 'Wallis and Futuna ' 'West Bank ' 'Western Sahara ' 'Yemen ' 'Zambia '
 'Zimbabwe ']
----------------------------------------------------------
Region|11|['ASIA (EX. NEAR EAST)         ' 'EASTERN EUROPE                     '
 'NORTHERN AFRICA                    '
 'OCEANIA                            '
 'WESTERN EUROPE                     '
 'SUB-SAHARAN AFRICA                 ' 'LATIN AMER. & CARIB    '
 'C.W. OF IND. STATES ' 'NEAR EAST                          '
 'NORTHERN AMERICA                   '
 'BALTICS                            ']
----------------------------------------------------------
Pop. Density (per sq. mi.)|219|['48,0' '124,6' '13,8' '290,4' '152,1' '9,7' '132,1' '156,0' '14,4' '99,9'
 '372,5' '2,6' '97,7' '91,9' '21,8' '1050,5' '1023,4' '649,5' '49,6'
 '340,0' '12,5' '69,8' '1241,0' '48,5' '8,2' '88,0' '2,7' '22,1' '151,0'
 '65,8' '66,6' '50,7' '290,7' '76,7' '36,5' '3,3' '104,4' '173,4' '6,9'
 '7,7' '21,3' '136,9' '38,3' '318,4' '26,7' '10,8' '89,1' '79,8' '54,8'
 '79,5' '102,7' '84,8' '129,8' '126,5' '21,2' '91,4' '188,5' '70,8' '47,8'
 '78,8' '324,3' '19,3' '39,5' '29,3' '66,3' '33,8' '15,5' '111,3' '2,2'
 '65,9' '5,3' '145,3' '3968,8' '66,9' '230,9' '93,6' '3989,7' '81,0' '0,0'
 '260,8' '254,4' '316,1' '112,9' '838,6' '39,4' '39,9' '3,6' '299,4'
 '65,4' '6355,7' '107,3' '2,9' '333,2' '127,9' '41,7' '61,3' '57,8'
 '131,9' '305,8' '193,0' '250,9' '337,4' '785,2' '64,0' '5,6' '59,6'
 '130,0' '191,8' '496,0' '135,7' '26,3' '26,9' '35,2' '27,3' '3,4' '212,4'
 '55,0' '183,5' '16183,0' '80,9' '31,7' '109,8' '74,0' '1196,7' '9,5'
 '1266,5' '5,1' '396,5' '3,1' '608,3' '538,1' '54,5' '153,9' '132,0'
 '16271,5' '1,8' '92,5' '74,4' '24,6' '2,5' '632,7' '192,2' '397,1'
 '231,0' '11,5' '15,2' '43,0' '9,9' '142,7' '172,9' '14,2' '14,6' '206,2'
 '44,9' '40,8' '12,3' '16,0' '22,0' '298,2' '123,3' '114,8' '284,8' '77,4'
 '312,9' '93,9' '8,4' '328,4' '18,2' '149,9' '273,5' '29,0' '303,0' '60,1'
 '479,5' '193,2' '61,1' '106,3' '179,2' '83,7' '6482,2' '111,4' '99,2'
 '19,4' '13,9' '36,2' '80,0' '308,2' '16,5' '65,5' '20,0' '182,2' '102,0'
 '640,3' '51,2' '39,6' '125,7' '153,3' '207,9' '62,2' '90,2' '10,3' '49,2'
 '454,2' '119,5' '31,4' '247,6' '31,0' '19,5' '61,0' '17,1' '28,2' '256,1'
 '56,9' '58,5' '419,9' '1,0' '40,6' '15,3' '31,3']
----------------------------------------------------------
Coastline (coast/area ratio)|151|['0,00' '1,26' '0,04' '58,29' '0,13' '59,80' '34,54' '0,18' '35,49' '0,34'
 '25,41' '24,21' '0,40' '22,51' '0,22' '1,68' '0,11' '194,34' '0,09'
 '52,29' '2,79' '0,32' '0,28' '0,24' '0,08' '2,02' '23,93' '61,07' '0,85'
 '0,15' '15,67' '0,05' '50,00' '2,52' '0,16' '10,32' '3,37' '7,01' '16,97'
 '1,37' '19,63' '2,64' '4,70' '0,79' '1,46' '1,06' '1,84' '8,39' '79,84'
 '6,18' '0,37' '0,63' '0,42' '60,60' '0,33' '0,71' '11,11' '0,44' '0,67'
 '0,23' '171,43' '10,37' '2,04' '35,17' '17,19' '23,20' '64,10' '0,97'
 '0,21' '6,38' '0,73' '67,12' '4,83' '2,85' '0,01' '2,06' '27,97' '1,31'
 '9,30' '7,87' '60,34' '0,03' '140,94' '2,07' '2,45' '2,80' '0,82' '2,16'
 '0,52' '0,10' '0,14' '146,43' '1,42' '214,67' '62,28' '3,12' '31,82'
 '0,07' '8,68' '49,52' '0,47' '870,66' '205,00' '39,22' '0,41' '0,31'
 '0,19' '142,86' '1,09' '37,92' '11,83' '5,63' '0,70' '310,69' '7,77'
 '0,98' '331,66' '3,18' '1,11' '12,10' '1,94' '3,63' '4,92' '8,22' '14,53'
 '51,72' '25,65' '49,59' '21,59' '13,69' '20,88' '0,27' '107,91' '0,56'
 '27,85' '18,67' '0,72' '4,35' '56,02' '7,06' '0,92' '90,47' '92,31'
 '0,46' '1,59' '5,08' '20,72' '1,05' '9,84' '47,08' '0,36']
----------------------------------------------------------
Net migration|157|['23,06' '-4,93' '-0,39' '-20,71' '6,6' '0' '10,76' '-6,15' '0,61' '-6,47'
 '3,98' '2' '-4,9' '-2,2' '1,05' '-0,71' '-0,31' '2,54' '1,23' '2,49'
 '-1,32' '0,31' '-0,03' '10,01' '3,59' '-4,58' '-1,8' '-0,06' '5,96'
 '-12,07' '18,75' '-0,11' '-0,4' '-0,17' nan '0,51' '-0,07' '1,58' '-1,58'
 '0,43' '0,97' '2,48' '-13,87' '-3,22' '-8,58' '-0,22' '-3,74' '-3,16'
 '1,41' '-3,14' '0,95' '0,66' '6,27' '2,94' '1,57' '1,6' '-4,7' '2,18'
 '-0,64' '2,35' '-8,37' '-13,92' '-0,15' '-1,67' '3,84' '-3,06' '-1,57'
 '-2,07' '-3,4' '-1,99' '5,24' '0,86' '2,38' '-0,84' '4,99' '5,36' '0,68'
 '2,07' '-4,92' '2,76' '6,59' '-3,35' '-0,1' '14,18' '-2,45' '-2,23'
 '-0,74' '4,85' '8,97' '4,86' '-1,45' '-0,33' '-6,04' '-0,05' '-0,9'
 '6,78' '-4,87' '-20,99' '-0,26' '7,75' '-0,98' '2,91' '-0,41' '4,05'
 '-1,22' '-0,67' '0,26' '9,61' '1,74' '0,28' '-2,77' '2,85' '-0,91'
 '-0,08' '-1,05' '-1,5' '-0,49' '3,57' '-1,46' '16,29' '-0,13' '1,02'
 '-7,11' '-2,67' '-4,86' '-7,64' '-11,7' '10,98' '-2,72' '-2,71' '0,2'
 '-1,33' '-5,69' '11,53' '0,3' '1,12' '5,37' '-0,29' '0,99' '-1,31'
 '-0,02' '-8,81' '1,67' '-2,86' '-2,06' '-10,83' '-0,57' '-0,86' '11,68'
 '1,03' '2,19' '3,41' '-0,32' '-1,72' '-0,04' '-0,45' '-8,94' '2,98']
----------------------------------------------------------
Infant mortality (per 1000 births)|220|['163,07' '21,52' '31' '9,27' '4,05' '191,19' '21,03' '19,46' '15,18'
 '23,28' '5,89' '4,69' '4,66' '81,74' '25,21' '17,27' '62,6' '12,5'
 '13,37' '4,68' '25,69' '85' '8,53' '100,44' '53,11' '21,05' '54,58'
 '29,61' '18,05' '12,61' '20,55' '97,57' '67,24' '69,29' '71,48' '68,26'
 '4,75' '47,77' '8,19' '91' '93,82' '8,8' '24,18' '20,97' '74,93' '94,69'
 '93,86' nan '9,95' '90,83' '6,84' '6,33' '7,18' '3,93' '4,56' '104,13'
 '14,15' '32,38' '47,41' '23,66' '32,59' '25,1' '85,13' '74,87' '7,87'
 '95,32' '6,24' '12,62' '3,57' '4,26' '12,07' '8,44' '53,64' '72,02'
 '22,93' '18,59' '4,16' '51,43' '5,13' '5,53' '15,82' '14,62' '8,6' '6,94'
 '35,93' '4,71' '90,37' '107,17' '33,26' '73,45' '29,32' '2,97' '8,57'
 '3,31' '56,29' '35,6' '41,58' '50,25' '5,39' '5,93' '7,03' '5,94' '12,36'
 '3,26' '5,24' '17,35' '29,21' '61,47' '48,52' '24,04' '7,05' '35,64'
 '85,22' '9,55' '24,52' '84,23' '128,87' '24,6' '4,7' '6,89' '4,81' '4,39'
 '10,09' '76,83' '103,32' '17,7' '56,52' '116,79' '3,89' '29,45' '7,09'
 '70,89' '15,03' '62,4' '20,91' '30,21' '40,42' '5,43' '53,79' '7,35'
 '41,62' '130,79' '48,98' '66,98' '5,04' '10,03' '7,72' '5,85' '29,11'
 '121,69' '98,8' '7,11' '3,7' '19,51' '72,44' '14,84' '20,47' '51,45'
 '25,63' '31,94' '23,51' '8,51' '5,05' '8,24' '18,61' '7,78' '26,43'
 '15,39' '91,23' '19' '14,49' '13,53' '7,54' '14,78' '27,71' '5,73'
 '43,11' '13,24' '55,51' '12,89' '15,53' '143,64' '2,29' '7,41' '4,45'
 '21,29' '116,7' '61,81' '4,42' '14,35' '62,5' '23,57' '69,27' '2,77'
 '29,53' '6,4' '110,76' '98,54' '20,48' '66,61' '24,31' '24,77' '41,04'
 '73,08' '15,67' '20,03' '67,83' '20,34' '14,51' '5,16' '6,5' '11,95'
 '71,1' '55,16' '22,2' '25,95' '8,03' '19,62' '61,5' '88,29' '67,69']
----------------------------------------------------------
Literacy (%)|140|['36,0' '86,5' '70,0' '97,0' '100,0' '42,0' '95,0' '89,0' '97,1' '98,6'
 '98,0' '95,6' '89,1' '43,1' '97,4' '99,6' '94,1' '40,9' '42,2' '87,2' nan
 '79,8' '86,4' '97,8' '93,9' '26,6' '85,3' '51,6' '69,4' '79,0' '76,6'
 '51,0' '47,5' '96,2' '90,9' '92,5' '56,5' '65,5' '83,8' '96,0' '50,9'
 '98,5' '97,6' '99,9' '67,9' '94,0' '84,7' '58,6' '57,7' '80,2' '85,7'
 '99,8' '42,7' '93,7' '99,0' '83,0' '63,2' '40,1' '74,8' '97,5' '90,0'
 '70,6' '35,9' '42,4' '98,8' '52,9' '76,2' '93,5' '99,4' '59,5' '87,9'
 '79,4' '40,4' '95,4' '91,3' '98,4' '85,1' '97,9' '83,5' '66,4' '87,4'
 '84,8' '57,5' '82,6' '94,5' '68,9' '62,7' '88,7' '97,2' '46,4' '92,8'
 '97,7' '41,7' '85,6' '92,2' '99,1' '51,7' '47,8' '84,0' '45,2' '96,7'
 '91,0' '67,5' '17,6' '68,0' '75,8' '45,7' '92,0' '92,6' '64,6' '93,3'
 '82,5' '88,9' '70,4' '67,0' '99,7' '79,3' '78,8' '40,2' '93,0' '58,0'
 '31,4' '37,8' '92,3' '61,1' '81,6' '76,9' '96,1' '78,2' '60,9' '74,2'
 '69,9' '77,9' '99,3' '53,0' '93,4' '90,3' '50,0' '50,2' '80,6' '90,7']
----------------------------------------------------------
Phones (per 1000)|214|['3,2' '71,2' '78,1' '259,5' '497,2' '7,8' '460,0' '549,9' '220,4' '195,7'
 '516,1' '565,5' '452,2' '137,1' '460,6' '281,3' '7,3' '481,9' '319,1'
 '462,6' '115,7' '9,7' '851,4' '14,3' '71,9' '215,4' '80,5' '225,3'
 '506,5' '237,2' '336,3' '7,0' '10,1' '3,4' '2,6' '5,7' '552,2' '169,6'
 '836,3' '2,3' '1,3' '213,0' '266,7' '176,2' '24,5' '0,2' '3,7' '289,9'
 '340,7' '14,6' '420,4' '74,7' nan '314,3' '614,6' '22,8' '304,8' '97,4'
 '125,6' '131,8' '142,4' '18,5' '7,9' '333,8' '8,2' '503,8' '112,6'
 '405,3' '586,4' '255,6' '194,5' '27,4' '26,8' '244,3' '146,6' '667,9'
 '14,4' '877,7' '589,7' '448,9' '364,5' '463,8' '492,0' '92,1' '842,4'
 '2,7' '7,4' '143,5' '16,9' '67,5' '546,7' '336,2' '647,7' '45,4' '52,0'
 '276,4' '38,6' '500,5' '676,0' '462,3' '430,9' '124,0' '461,2' '811,3'
 '104,5' '164,1' '8,1' '42,7' '42,4' '486,1' '211,0' '84,0' '14,1' '321,4'
 '23,7' '127,1' '585,5' '223,4' '515,4' '384,9' '260,0' '3,6' '179,0'
 '90,0' '6,4' '505,0' '91,2' '394,4' '12,9' '289,3' '49,7' '181,6' '114,8'
 '208,1' '1035,6' '55,1' '40,4' '3,5' '62,6' '143,0' '15,9' '460,8'
 '365,3' '252,2' '441,7' '39,7' '1,9' '9,3' '254,7' '461,7' '85,5' '31,8'
 '325,6' '137,9' '10,9' '49,2' '79,5' '38,4' '306,3' '399,2' '283,1'
 '232,0' '380,9' '196,9' '280,6' '293,3' '638,9' '303,3' '683,2' '190,9'
 '75,2' '704,3' '36,2' '140,6' '22,2' '285,8' '262,4' '4,0' '411,4'
 '220,1' '406,1' '13,4' '11,3' '107,0' '453,5' '61,5' '16,3' '184,7'
 '30,8' '715,0' '680,9' '153,8' '591,0' '33,5' '108,9' '10,6' '97,7'
 '303,5' '123,6' '269,5' '74,6' '59,3' '259,9' '475,3' '543,5' '898,0'
 '291,4' '62,9' '32,6' '140,1' '187,7' '652,8' '118,6' '145,2' '37,2']
----------------------------------------------------------
Arable (%)|203|['12,13' '21,09' '3,22' '10' '2,22' '2,41' '0' '18,18' '12,31' '17,55'
 '10,53' '6,55' '16,91' '19,63' '0,8' '2,82' '62,11' '37,21' '29,55'
 '23,28' '2,85' '18,08' '20' '3,09' '2,67' '13,6' '0,65' '6,96' '0,57'
 '40,02' '14,43' '15,19' '35,05' '20,96' '12,81' '4,96' '9,68' '3,85'
 '3,1' '2,86' '2,65' '15,4' '2,42' '35,87' '2,96' '0,51' '17,39' '4,41'
 '9,75' '26,09' '33,05' '7,79' '39,8' '54,02' '0,04' '6,67' '22,65' '4,71'
 '5,85' '2,87' '31,85' '4,63' '4,95' '16,04' '10,71' '2,14' '10,95' '7,19'
 '33,53' '0,14' '0,82' '1,26' '25' '28,95' '11,44' '33,85' '16,26' '21,1'
 '5,88' '11,24' '9,09' '12,54' nan '3,63' '10,67' '2,44' '28,3' '9,55'
 '5,05' '50,09' '0,07' '54,4' '11,32' '8,72' '13,15' '15,2' '9' '16,39'
 '27,79' '16,07' '12,19' '7,98' '8,08' '2,74' '20,76' '17,18' '0,73' '7,3'
 '3,8' '29,67' '16,62' '10,87' '3,95' '1,03' '45,22' '22,26' '5,07'
 '23,38' '5,48' '13,33' '3,82' '28,13' '16,67' '10,38' '0,48' '49,26'
 '12,99' '5,71' '55,3' '0,77' '19,61' '5,1' '0,99' '21,68' '26,71' '0,38'
 '5,6' '15,94' '3,54' '31,29' '13,04' '27,87' '8,7' '7,36' '0,46' '7,6'
 '2,89' '18,95' '45,91' '21,75' '1,64' '40,82' '7,33' '40,54' '12,9'
 '19,44' '6,56' '17,95' '21,2' '6,25' '1,67' '12,78' '33,35' '6,98'
 '30,16' '8,6' '0,64' '12,08' '26,07' '13,86' '6,83' '0,37' '10,35' '6,54'
 '10,42' '25,22' '24' '6,61' '4,52' '29,36' '46,15' '23,61' '14,62'
 '17,86' '30,93' '3,72' '2,33' '25,88' '56,21' '0,6' '23,46' '19,13'
 '7,43' '10,83' '2,46' '2,95' '19,97' '11,76' '5' '16,9' '0,02' '2,78'
 '7,08' '8,32']
----------------------------------------------------------
Crops (%)|162|['0,22' '4,42' '0,25' '15' '0' '0,24' '4,55' '0,48' '2,3' '0,04' '0,86'
 '2,71' '0,4' '5,63' '3,07' '2,33' '0,6' '1,71' '2,4' '0,43' '0,19' '2,96'
 '0,01' '0,9' '6,67' '0,76' '1,92' '0,97' '14,02' '0,61' '2,58' '0,02'
 '0,5' '0,14' '0,42' '1,25' '1,67' '23,32' '0,52' '0,13' '13,04' '5,88'
 '13,84' '2,27' '7,6' '4,44' '3,05' '20' '10,33' '0,67' '4,93' '12,07'
 '3,57' '0,03' '0,45' '0,75' '4,65' '2,07' '0,05' '5,46' '0,66' '21,05'
 '3,86' '0,59' '9,67' '8,78' '29,41' '3,55' '16,36' '5,03' nan '8,82'
 '0,15' '11,61' '3,22' '1,01' '2,06' '2,74' '7,23' '1,39' '0,78' '4,17'
 '9,53' '10,16' '0,96' '1,83' '0,98' '50,68' '2,49' '1,95' '0,11' '0,35'
 '0,47' '13,98' '2,28' '0,91' '1,81' '1,03' '1,49' '17,61' '16,67' '3,13'
 '38,89' '9,43' '1,31' '45,71' '10,79' '2,17' '0,3' '0,64' '0,33' '6,99'
 '1,94' '4,35' '0,87' '1,98' '1,44' '0,23' '16,77' '1,12' '7,81' '5,52'
 '0,27' '1,2' '2,25' '12,16' '2,78' '22,95' '17,95' '24,38' '48,96' '0,09'
 '0,21' '3,2' '13,33' '0,89' '2,62' '2' '0,79' '9,87' '15,7' '0,18' '0,06'
 '0,7' '4,43' '1' '0,92' '1,08' '6,46' '2,21' '43,06' '9,16' '13,74'
 '3,31' '10,65' '1,61' '0,83' '7,38' '5,95' '2,94' '25' '18,97' '0,34']
----------------------------------------------------------
Other (%)|209|['87,65' '74,49' '96,53' '75' '97,78' '97,35' '100' '77,27' '87,21'
 '80,15' '89,47' '93,41' '82,23' '77,66' '98,8' '91,55' '34,82' '60,46'
 '69,85' '76,32' '95,44' '79,52' '80' '96,48' '97,14' '83,44' '99,34'
 '92,15' '73,33' '98,67' '58,06' '85,38' '83,84' '50,93' '78,43' '84,61'
 '95,02' '89,82' '96,15' '96,76' '97,12' '96,93' '83,35' '95,91' '40,81'
 '96,52' '99,36' '69,57' '89,71' '76,41' '71,65' '59,35' '87,77' '57,15'
 '45,79' '99,96' '67,02' '94,62' '89,22' '96,65' '56,08' '91,8' '83,51'
 '88,54' '97,86' '84,4' '92,78' '64,4' '99,81' '93,72' '98,08' '74,5' '50'
 '84,7' '65,56' '74,07' '70,12' '64,71' '85,21' '74,55' '82,43' nan
 '93,79' '80,51' '97,41' '60,09' '87,23' '93,94' '47,85' '99,93' '42,86'
 '81,45' '89,89' '86,07' '84,77' '91' '79,44' '62,68' '73,77' '86,85'
 '95,5' '91,97' '90,94' '46,58' '76,75' '80,87' '99,16' '92,35' '95,85'
 '69,86' '69,4' '89' '93,77' '98,78' '53,87' '75,93' '93,91' '75,13'
 '76,91' '70' '68,74' '44,44' '80,19' '99,51' '47,78' '85,7' '48,58'
 '33,91' '99,23' '78,22' '94,6' '99,01' '77,68' '72,32' '90' '99,29'
 '87,41' '82,12' '96,45' '65,75' '82,61' '97,13' '99,74' '71,26' '86,95'
 '90,66' '98,1' '92,17' '96,71' '64,28' '52,97' '70,44' '90,53' '98,09'
 '85,2' '56,93' '92,56' '47,3' '87,1' '77,78' '70,49' '86,96' '64,1'
 '54,42' '83,33' '44,79' '98,24' '87,01' '63,45' '84,45' '92,13' '98,36'
 '67,22' '89,91' '97,36' '98,29' '87,13' '64,06' '92,99' '99,57' '88,95'
 '93,45' '88,97' '70,35' '92,47' '94,4' '64,18' '51,64' '33,33' '76,22'
 '68,4' '65,76' '96,14' '97,67' '63,47' '42,18' '97,15' '76,33' '80,65'
 '92,34' '88,34' '90,16' '96,13' '74,08' '85,3' '64,13' '99,98' '96,98'
 '92,9' '91,34']
----------------------------------------------------------
Climate|6|['1' '3' '2' nan '4' '1,5' '2,5']
----------------------------------------------------------
Birthrate|220|['46,6' '15,11' '17,14' '22,46' '8,71' '45,11' '14,17' '16,93' '16,73'
 '12,07' '11,03' '12,14' '8,74' '20,74' '17,57' '17,8' '29,8' '12,71'
 '11,16' '10,38' '28,84' '38,85' '11,4' '33,65' '23,3' '8,77' '23,08'
 '16,56' '14,89' '18,79' '9,65' '45,62' '17,91' '42,22' '26,9' '33,89'
 '10,78' '24,87' '12,74' '33,91' '45,73' '15,23' '13,25' '20,48' '36,93'
 '43,69' '42,57' '21' '18,32' '35,11' '9,61' '11,89' '12,56' '9,02'
 '11,13' '39,53' '15,27' '23,22' '26,99' '22,29' '22,94' '26,61' '35,59'
 '34,33' '10,04' '37,98' '14,05' '22,55' '10,45' '11,99' '20,46' '16,68'
 '36,16' '39,37' '39,45' '10,41' '8,25' '30,52' '10,74' '9,68' '15,93'
 '22,08' '15,05' '29,88' '8,81' '41,76' '37,22' '18,28' '36,44' '28,24'
 '7,29' '9,72' '13,64' '22,01' '20,34' '17' '31,98' '14,45' '11,05'
 '17,97' '8,72' '20,82' '9,37' '9,3' '21,25' '16' '39,72' '30,65' '15,54'
 '10' '21,94' '22,8' '35,49' '9,24' '18,52' '24,75' '44,77' '26,49'
 '10,21' '8,75' '11,94' '8,48' '12,02' '41,41' '43,13' '22,86' '34,81'
 '49,82' '10,22' '33,05' '13,74' '40,99' '15,43' '40,95' '20,69' '24,68'
 '15,7' '9,19' '21,59' '17,59' '21,98' '35,18' '24,32' '24,76' '30,98'
 '10,9' '14,78' '18,11' '13,76' '24,51' '50,73' '40,43' '19,43' '11,46'
 '36,24' '29,74' '18,03' '21,74' '29,36' '29,1' '24,89' '9,85' '10,72'
 '12,77' '15,56' '18,9' '10,7' '9,95' '40,37' '12,13' '18,02' '19,68'
 '13,52' '16,18' '16,43' '10,02' '40,25' '29,34' '32,78' nan '16,03'
 '45,76' '9,34' '10,65' '8,98' '30,01' '45,13' '18,2' '10,06' '15,51'
 '34,53' '27,41' '10,27' '9,71' '27,76' '32,65' '37,71' '13,87' '37,01'
 '25,37' '12,9' '15,52' '16,62' '27,61' '21,84' '22,18' '47,35' '8,82'
 '18,96' '10,71' '14,14' '13,91' '26,36' '22,72' '18,71' '16,86' '13,96'
 '31,67' '42,89' '41' '28,01']
----------------------------------------------------------
Deathrate|201|['20,34' '5,22' '4,61' '3,27' '6,25' '24,2' '5,34' '5,37' '7,55' '8,23'
 '6,68' '7,51' '9,76' '9,75' '9,05' '4,14' '8,27' '8,67' '14,02' '10,27'
 '5,72' '12,22' '7,74' '12,7' '7,53' '29,5' '6,17' '4,42' '3,45' '14,27'
 '15,6' '9,83' '13,46' '9,06' '13,47' '7,8' '6,55' '4,89' '18,65' '16,38'
 '5,81' '6,97' '5,58' '8,2' '13,27' '12,93' nan '4,36' '14,84' '11,48'
 '7,22' '7,68' '10,59' '10,36' '19,31' '6,73' '5,73' '6,24' '4,23' '5,23'
 '5,78' '15,06' '9,6' '13,25' '14,86' '8,7' '5,65' '9,86' '9,14' '4,88'
 '4,69' '12,25' '3,8' '9,23' '10,62' '9,72' '9,31' '10,24' '7,84' '6,88'
 '6,09' '4,48' '5,2' '10,01' '15,48' '16,53' '8,28' '12,17' '5,28' '6,29'
 '13,11' '6,72' '8,18' '5,55' '7,82' '11,19' '6,18' '10,4' '6,52' '9,16'
 '9,28' '2,65' '9,42' '8,26' '7,13' '5,85' '2,41' '7,08' '11,55' '13,66'
 '6,21' '28,71' '23,1' '3,48' '7,18' '10,98' '8,41' '4,47' '8,77' '11,11'
 '19,33' '5,05' '7,06' '16,89' '8,1' '4,78' '6,48' '12,16' '6,86' '7,7'
 '4,74' '4,75' '12,64' '12,91' '6,95' '7,1' '21,35' '18,86' '6,7' '8,68'
 '6,45' '5,69' '4,45' '20,91' '16,94' '2,29' '9,4' '3,81' '6,8' '5,36'

In [106]:
df['Country'].value_counts()
df['Country']=df['Country'].str.strip(' ')

In [107]:
df['Region'].value_counts()
df['Region']=df['Region'].str.strip(' ')
df['Region'].dtype

dtype('O')

In [108]:
# df['Pop. Density (per sq. mi.)']=df['Pop. Density (per sq. mi.)'].replace(',','.',regex=True).astype('float')
# df['Pop. Density (per sq. mi.)']

In [109]:
# df['Coastline (coast/area ratio)']=df['Coastline (coast/area ratio)'].replace(',','.',regex=True).astype('float')
# df['Coastline (coast/area ratio)']

In [110]:
# df[['Infant mortality (per 1000 births)','Literacy (%)']]=df[['Infant mortality (per 1000 births)','Literacy (%)']].replace(',','.',regex=True).astype('float')
# df[['Infant mortality (per 1000 births)','Literacy (%)']]

In [111]:
df[['Pop. Density (per sq. mi.)','Coastline (coast/area ratio)','Infant mortality (per 1000 births)','Literacy (%)','Phones (per 1000)','Arable (%)','Crops (%)','Other (%)','Climate','Birthrate','Deathrate','Agriculture','Industry','Service','Net migration']]=df[['Pop. Density (per sq. mi.)','Coastline (coast/area ratio)','Infant mortality (per 1000 births)','Literacy (%)','Phones (per 1000)','Arable (%)','Crops (%)','Other (%)','Climate','Birthrate','Deathrate','Agriculture','Industry','Service','Net migration']].replace(',','.',regex=True).astype('float')
df[['Pop. Density (per sq. mi.)','Coastline (coast/area ratio)','Infant mortality (per 1000 births)','Literacy (%)','Phones (per 1000)','Arable (%)','Crops (%)','Other (%)','Climate','Birthrate','Deathrate','Agriculture','Industry','Service','Net migration']]

,Pop. Density (per sq. mi.),Coastline (coast/area ratio),Infant mortality (per 1000 births),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service,Net migration
0,48.0,0.00,163.07,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380,23.06
1,124.6,1.26,21.52,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579,-4.93
2,13.8,0.04,31.00,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298,-0.39
3,290.4,58.29,9.27,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,NaN,NaN,NaN,-20.71
4,152.1,0.00,4.05,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,NaN,NaN,NaN,6.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,419.9,0.00,19.62,NaN,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630,2.98
223,1.0,0.42,NaN,NaN,NaN,0.02,0.00,99.98,1.0,NaN,NaN,NaN,NaN,0.400,NaN
224,40.6,0.36,61.50,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393,0.00
225,15.3,0.00,88.29,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489,0.00
226,31.3,0.00,67.69,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579,0.00

In [112]:
object_col=[]
for i in df:
  if df[i].dtype=='object':
    object_col.append(i)
    print(f'{i}|{df[i].nunique()}|{df[i].unique()}')
    print('----------------------------------------------------------')

Country|227|['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua & Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia'
 'Austria' 'Azerbaijan' 'Bahamas, The' 'Bahrain' 'Bangladesh' 'Barbados'
 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia & Herzegovina' 'Botswana' 'Brazil' 'British Virgin Is.' 'Brunei'
 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Rep.' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo, Dem. Rep.'
 'Congo, Repub. of the' 'Cook Islands' 'Costa Rica' "Cote d'Ivoire"
 'Croatia' 'Cuba' 'Cyprus' 'Czech Republic' 'Denmark' 'Djibouti'
 'Dominica' 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Ethiopia'
 'Faroe Islands' 'Fiji' 'Finland' 'France' 'French Guiana'
 'French Polynesia' 'Gabon' 'Gambia, The' 'Gaza Strip' 'Georgia' 'Germany'
 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy' 'Jamaica' 'Japan'
 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Korea, North'
 'Korea, South' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Macau'
 'Macedonia' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mauritius' 'Mayotte'
 'Mexico' 'Micronesia, Fed. St.' 'Moldova' 'Monaco' 'Mongolia'
 'Montserrat' 'Morocco' 'Mozambique' 'Namibia' 'Nauru' 'Nepal'
 'Netherlands' 'Netherlands Antilles' 'New Caledonia' 'New Zealand'
 'Nicaragua' 'Niger' 'Nigeria' 'N. Mariana Islands' 'Norway' 'Oman'
 'Pakistan' 'Palau' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion'
 'Romania' 'Russia' 'Rwanda' 'Saint Helena' 'Saint Kitts & Nevis'
 'Saint Lucia' 'St Pierre & Miquelon' 'Saint Vincent and the Grenadines'
 'Samoa' 'San Marino' 'Sao Tome & Principe' 'Saudi Arabia' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Swaziland' 'Sweden' 'Switzerland' 'Syria' 'Taiwan'
 'Tajikistan' 'Tanzania' 'Thailand' 'Togo' 'Tonga' 'Trinidad & Tobago'
 'Tunisia' 'Turkey' 'Turkmenistan' 'Turks & Caicos Is' 'Tuvalu' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'United States'
 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam' 'Virgin Islands'
 'Wallis and Futuna' 'West Bank' 'Western Sahara' 'Yemen' 'Zambia'
 'Zimbabwe']
----------------------------------------------------------
Region|11|['ASIA (EX. NEAR EAST)' 'EASTERN EUROPE' 'NORTHERN AFRICA' 'OCEANIA'
 'WESTERN EUROPE' 'SUB-SAHARAN AFRICA' 'LATIN AMER. & CARIB'
 'C.W. OF IND. STATES' 'NEAR EAST' 'NORTHERN AMERICA' 'BALTICS']
----------------------------------------------------------

-- 1)Add a column for GDP per capita:

 ALTER TABLE `countries of the world`
 ADD COLUMN GDP_per_Capita FLOAT;

UPDATE `countries of the world`
SET GDP_per_Capita = `GDP ($ per capita)` / Population;

select Country,`GDP ($ per capita)` from `countries of the world`;

-- 2)Create a categorical column for population density:

ALTER TABLE `countries of the world`
ADD COLUMN Density_Category VARCHAR(50);

UPDATE `countries of the world`
SET Density_Category = CASE
    WHEN `Pop. Density (per sq. mi.)` < 50 THEN 'Low'
    WHEN `Pop. Density (per sq. mi.)` BETWEEN 50 AND 200 THEN 'Medium'
    ELSE 'High'
END;

UPDATE countries of the world SET Density_Category = CASE WHEN Pop. Density (per sq. mi.) < 50 THEN
'Low' WHEN Pop. Density (per sq. mi.) BETWEEN 50 AND 200 THEN 'Medium' ELSE 'High' END;

df[Density_Category]=np.where(df['Pop. Density (per sq. mi.)']<=50,Low) this can also be used in true false condition
  

-- 3)Extract the continent from the region:

ALTER TABLE `countries of the world`
ADD COLUMN Continent VARCHAR(50);

UPDATE `countries of the world`
SET Continent = CASE
    WHEN Region LIKE '%Asia%' or Region LIKE '%Near East%' THEN 'Asia'
    WHEN Region LIKE '%Africa%' THEN 'Africa'
    WHEN Region LIKE '%Europe%' THEN 'Europe'
    WHEN Region LIKE '%Americas%' THEN 'North America'
    WHEN Region LIKE '%Latin Amer. & Carib%' THEN 'South America'
    WHEN Region LIKE '%Oceania%' THEN 'Oceania'
    ELSE 'Other'
END;


-- 4) Climate

ALTER TABLE `countries of the world`
ADD COLUMN Climate_category VARCHAR(50);

UPDATE `countries of the world`
SET
    Climate_category = CASE
        WHEN Climate = 1 THEN 'Tropical'
        WHEN Climate = 2 THEN 'Arid'
        WHEN Climate = 3 THEN 'Temperate'
        WHEN Climate = 4 THEN 'Cold'
        ELSE 'Unknown'
    END;-- Handle any other values not explicitly mapped

In [113]:
# Creating a new column 'Density_category' based on a condition
df['Density_category'] = 'High'  # Initialize the 'Density_category' column with 'High' as the default value

# # Using DataFrame.loc[] to set values based on the condition
df.loc[df['Pop. Density (per sq. mi.)'] < 50, 'Density_category'] = 'Low'
df.loc[(df['Pop. Density (per sq. mi.)'] >=50) & (df['Pop. Density (per sq. mi.)'] <=200), 'Density_category'] = 'Medium'

# # Displaying the modified dataframe
print(df['Density_category'])

0         Low
1      Medium
2         Low
3        High
4      Medium
        ...
222      High
223       Low
224       Low
225       Low
226       Low
Name: Density_category, Length: 227, dtype: object

In [114]:
df['GDP_per_Capita'] = df['GDP ($ per capita)']/ df['Population']
df['GDP_per_Capita']

0      0.000023
1      0.001256
2      0.000182
3      0.138423
4      0.266850
         ...
222    0.000325
223         NaN
224    0.000037
225    0.000070
226    0.000155
Name: GDP_per_Capita, Length: 227, dtype: float64

In [115]:

df['Climate_category']='Unknown'
df.loc[df['Climate'] == 1, 'Climate_category'] = 'Tropical'
df.loc[df['Climate'] == 2, 'Climate_category'] = 'Arid'
df.loc[df['Climate'] == 3, 'Climate_category'] = 'Temperate'
df.loc[df['Climate'] == 4, 'Climate_category'] = 'Cold'
df['Climate_category']

0       Tropical
1      Temperate
2       Tropical
3           Arid
4      Temperate
         ...
222    Temperate
223     Tropical
224     Tropical
225         Arid
226         Arid
Name: Climate_category, Length: 227, dtype: object

In [116]:
df['Continent']='Others'
df.loc[(df['Region'] == 'ASIA (EX. NEAR EAST)') | (df['Region'] == 'NEAR EAST'), 'Continent'] = 'Asia'
df.loc[(df['Region']=='NORTHERN AFRICA')|(df['Region']=='SUB-SAHARAN AFRICA'),'Continent']='Africa'
df.loc[(df['Region']=='WESTERN EUROPE')|(df['Region']=='EASTERN EUROPE'),'Continent']='Europe'
df.loc[df['Region']=='NORTHERN AMERICA','Continent']='North America'
df.loc[df['Region']=='LATIN AMER. & CARIB','Continent']='South America'
df.loc[df['Region']=='OCEANIA','Continent']='Oceania'
df['Continent'].value_counts()

Continent
Africa           57
South America    45
Asia             44
Europe           40
Oceania          21
Others           15
North America     5
Name: count, dtype: int64

**EDA**

In [117]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),...,Climate,Birthrate,Deathrate,Agriculture,Industry,Service,Density_category,GDP_per_Capita,Climate_category,Continent
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,...,1.0,46.60,20.34,0.380,0.240,0.380,Low,0.000023,Tropical,Asia
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,...,3.0,15.11,5.22,0.232,0.188,0.579,Medium,0.001256,Temperate,Europe
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,...,1.0,17.14,4.61,0.101,0.600,0.298,Low,0.000182,Tropical,Africa
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,...,2.0,22.46,3.27,NaN,NaN,NaN,High,0.138423,Arid,Oceania
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,...,3.0,8.71,6.25,NaN,NaN,NaN,Medium,0.266850,Temperate,Europe

The .idxmax() function in pandas is used to return the index (or label) of the first occurrence of the maximum value along an axis. When used on a DataFrame column, it returns the index of the row where the maximum value is found.

In [118]:
#1.Which countries have the highest and lowest populations?

print(df.loc[df['Population'].idxmax(), ['Country', 'Population']])
print()
print(df.loc[df['Population'].idxmin(), ['Country', 'Population']])

Country            China
Population    1313973713
Name: 42, dtype: object

Country       St Pierre & Miquelon
Population                    7026
Name: 174, dtype: object

In [119]:
#2.What are the largest and smallest countries by land area?
print(df.loc[df['Area (sq. mi.)'].idxmax(),['Country','Area (sq. mi.)']])
print()
print(df.loc[df['Area (sq. mi.)'].idxmin(),['Country','Area (sq. mi.)']])

Country             Russia
Area (sq. mi.)    17075200
Name: 169, dtype: object

Country           Monaco
Area (sq. mi.)         2
Name: 138, dtype: object

In [120]:
#3.What are the top 10 countries by GDP and which country has the maximum GDP growth ?
df.nlargest(10, 'GDP ($ per capita)')[['Country', 'GDP ($ per capita)']]

            Country  GDP ($ per capita)
121      Luxembourg             55100.0
154          Norway             37800.0
214   United States             37800.0
22          Bermuda             36000.0
38   Cayman Islands             35000.0
177      San Marino             34600.0
196     Switzerland             32700.0
54          Denmark             31100.0
93          Iceland             30900.0
12          Austria             30000.0

In [121]:
#4.What is the average population density across all countries?
df['Pop. Density (per sq. mi.)'].mean()

379.0471365638766

In [122]:
#5.Which country is having the highest infant mortality rate?
df.loc[df['Infant mortality (per 1000 births)'].idxmax(), ['Country','Infant mortality (per 1000 births)']]

Country                               Angola
Infant mortality (per 1000 births)    191.19
Name: 5, dtype: object

In [123]:
#6.What is the average literacy rate by region?
df.groupby('Region')['Literacy (%)'].mean().sort_values(ascending=False)

Region
BALTICS                 99.733333
C.W. OF IND. STATES     98.725000
WESTERN EUROPE          98.391304
NORTHERN AMERICA        97.750000
EASTERN EUROPE          97.088889
LATIN AMER. & CARIB     90.654545
OCEANIA                 88.835294
ASIA (EX. NEAR EAST)    79.553571
NEAR EAST               79.521429
NORTHERN AFRICA         67.240000
SUB-SAHARAN AFRICA      62.510000
Name: Literacy (%), dtype: float64

In [124]:
#7.Which country has the lowest rates of mobile phone usage?
df.loc[df['Phones (per 1000)'].idxmin(),['Country','Phones (per 1000)']]

Country              Congo, Dem. Rep.
Phones (per 1000)                 0.2
Name: 45, dtype: object

In [125]:
#8.What is the birth and Death rate for each Continents
df.groupby('Continent')[['Birthrate', 'Deathrate']].mean()

               Birthrate  Deathrate
Continent
Africa         34.684107  14.235536
Asia           22.566591   6.608864
Europe         10.502051   9.616923
North America  13.154000   7.694000
Oceania        22.108000   5.810526
Others         16.153333  10.799333
South America  19.081111   6.376000

In [126]:
#9.Literacy rate varies across different Continents?
df.groupby('Continent')['Literacy (%)'].mean()

Continent
Africa           62.940000
Asia             79.542857
Europe           98.025000
North America    97.750000
Oceania          88.835294
Others           98.926667
South America    90.654545
Name: Literacy (%), dtype: float64

In [127]:
#10.How many countries are included in the dataset?
df['Country'].nunique()

227

In [128]:
# 11.Total Population by Region
df.groupby('Region')['Population'].sum()

Region
ASIA (EX. NEAR EAST)    3687982236
BALTICS                    7184974
C.W. OF IND. STATES      280081548
EASTERN EUROPE           119914717
LATIN AMER. & CARIB      561824599
NEAR EAST                195068377
NORTHERN AFRICA          161407133
NORTHERN AMERICA         331672307
OCEANIA                   33131662
SUB-SAHARAN AFRICA       749437000
WESTERN EUROPE           396339998
Name: Population, dtype: int64

In [129]:
#12.Population Density Analysis
df['Population Density']= df['Population'] / df['Area (sq. mi.)']
df.nlargest(10, 'Population Density')[['Country', 'Population Density']]

        Country  Population Density
138      Monaco        16271.500000
122       Macau        16183.035714
184   Singapore         6482.178932
91    Hong Kong         6355.706960
78    Gibraltar         3989.714286
74   Gaza Strip         3968.769444
129       Malta         1266.500000
22      Bermuda         1241.000000
127    Maldives         1196.693333
15      Bahrain         1050.503759

In [130]:
#13. When considering the coastline, find the countries with the LONGEST coastlines.
df.loc[df['Coastline (coast/area ratio)'].idxmax(),['Country','Coastline (coast/area ratio)']]

Country                         Micronesia, Fed. St.
Coastline (coast/area ratio)                  870.66
Name: 136, dtype: object

In [131]:
#14. Find the countries with the most and least migrants.
print(df.loc[df['Net migration'].idxmax(),['Country','Net migration']])
print()
print(df.loc[df['Net migration'].idxmin(),['Country','Net migration']])

Country          Afghanistan
Net migration          23.06
Name: 0, dtype: object

Country          Micronesia, Fed. St.
Net migration                  -20.99
Name: 136, dtype: object

In [132]:
#15. Find the continent with the most and least migrants.
continent_migration_sum=df.groupby('Continent')['Net migration'].sum()
print(continent_migration_sum)
print()
print('Continent with Most Migrants:',continent_migration_sum.idxmax(), continent_migration_sum.max())
print()
print('Continent with Least Migrants:',continent_migration_sum.idxmin(), continent_migration_sum.max())

Continent
Africa          -19.25
Asia             80.83
Europe           85.23
North America    -1.37
Oceania         -39.15
Others          -30.50
South America   -67.25
Name: Net migration, dtype: float64

Continent with Most Migrants: Europe 85.23

Continent with Least Migrants: South America 85.23

In [133]:
#16) Average GDP per Capita by Continent
df.groupby('Continent')['GDP_per_Capita'].mean().sort_values(ascending=False)

Continent
North America    0.377057
Europe           0.132497
Oceania          0.097634
South America    0.096716
Africa           0.008985
Asia             0.004942
Others           0.001489
Name: GDP_per_Capita, dtype: float64

In [134]:
#17) Highest GDP per Capita in Each Continent
df.loc[df.groupby('Continent')['GDP_per_Capita'].idxmax(),['Continent', 'Country', 'GDP_per_Capita']]

         Continent               Country  GDP_per_Capita
171         Africa          Saint Helena        0.333244
29            Asia                Brunei        0.049019
177         Europe            San Marino        1.182866
174  North America  St Pierre & Miquelon        0.982067
157        Oceania                 Palau        0.437339
64          Others               Estonia        0.009288
38   South America        Cayman Islands        0.770314

In [135]:
#18)Distribution of Density Categories
df['Density_category'].value_counts()

Density_category
Medium    92
Low       82
High      53
Name: count, dtype: int64

In [136]:
#climate
df.groupby(['Continent', 'Climate_category']).size().reset_index(name='Number_of_Countries')

        Continent Climate_category  Number_of_Countries
0          Africa             Arid                   33
1          Africa        Temperate                    4
2          Africa         Tropical                   10
3          Africa          Unknown                   10
4            Asia             Arid                   18
5            Asia        Temperate                    8
6            Asia         Tropical                   14
7            Asia          Unknown                    4
8          Europe             Cold                    3
9          Europe        Temperate                   27
10         Europe          Unknown                   10
11  North America             Arid                    1
12  North America        Temperate                    1
13  North America         Tropical                    1
14  North America          Unknown                    2
15        Oceania             Arid                   19
16        Oceania        Temperate                    1
17        Oceania         Tropical                    1
18         Others             Arid                    1
19         Others             Cold                    3
20         Others        Temperate                    4
21         Others         Tropical                    3
22         Others          Unknown                    4
23  South America             Arid                   39
24  South America        Temperate                    3
25  South America          Unknown                    3